apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: simple-server
    name: simple-server
spec:
    replicas: 1
    selector:
        matchLabels:
            app: simple-server
    template:
        metadata:
            labels:
                app: simple-server
        spec:
            containers:
                - image: hong9lol/simple_app:latest
                  imagePullPolicy: IfNotPresent
                  name: simple-server-container
                  ports:
                      - containerPort: 8080
                  readinessProbe:
                      failureThreshold: 10
                      httpGet:
                          path: /healthz
                          port: 8080
                      initialDelaySeconds: 1
                      periodSeconds: 5
                  resources:
                      limits:
                          cpu: 300m
                          memory: 128Mi
                      requests:
                          cpu: 200m
                          memory: 64Mi
                # - image: nginx:latest
                #   name: simple-server-container2
                #   resources:
                #       limits:
                #           cpu: 100m
                #           memory: 128Mi
                #       requests:
                #           cpu: 100m
                #           memory: 64Mi
            imagePullSecrets:
                - name: secret-jake
