apiVersion: apps/v1
kind: Deployment
metadata:
    name: upstream-controller
    namespace: upstream-system
    labels:
        k8s-app: upstream-controller
spec:
    selector:
        matchLabels:
            name: upstream-controller
    template:
        metadata:
            labels:
                name: upstream-controller
        spec:
            tolerations:
                - key: node-role.kubernetes.io/master
                  effect: NoSchedule
            containers:
                - name: controller
                  image: hong9lol/upstream-controller:0.1
                  #   image: 127.0.0.1:5000/upstream-controller:0.1
                  imagePullPolicy: IfNotPresent
                  #   imagePullPolicy: Always
                  ports:
                      - name: http
                        containerPort: 5001
                        protocol: TCP
                  volumeMounts:
                      - name: timelog
                        mountPath: /host/log
                  securityContext:
                      privileged: true
            imagePullSecrets:
                - name: secret-jake
            volumes:
                - name: timelog
                  hostPath:
                      path: /home/leejaehong/log
                      type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
    name: upstream-controller # 서비스의 이름
    namespace: upstream-system
spec:
    selector:
        name: upstream-controller # Deployment의 Pod를 선택하기 위한 라벨 셀렉터
    ports:
        - protocol: TCP
          port: 5001 # 서비스가 리스닝하는 포트
          targetPort: 5001 # Pod 내부의 컨테이너에서 수신하는 포트
    type: LoadBalancer # 서비스 유형
