kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

kubeadmConfigPatches:
    - |
        kind: ClusterConfiguration
        controllerManager:
          extraArgs:
            horizontal-pod-autoscaler-sync-period: "1s"
nodes:
    - role: control-plane
      kubeadmConfigPatches:
          - |
              kind: InitConfiguration
              nodeRegistration:
                kubeletExtraArgs:
                  anonymous-auth: "true"
                  authorization-mode: "AlwaysAllow"
    - role: worker
      kubeadmConfigPatches:
          - |
              kind: InitConfiguration
              nodeRegistration:
                kubeletExtraArgs:
                  anonymous-auth: "true"
                  authorization-mode: "AlwaysAllow"
    - role: worker
      kubeadmConfigPatches:
          - |
              kind: InitConfiguration
              nodeRegistration:
                kubeletExtraArgs:
                  anonymous-auth: "true"
                  authorization-mode: "AlwaysAllow"
    - role: worker
      kubeadmConfigPatches:
          - |
              kind: InitConfiguration
              nodeRegistration:
                kubeletExtraArgs:
                  anonymous-auth: "true"
                  authorization-mode: "AlwaysAllow"
