kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
    - role: control-plane
      extraMounts:
          - hostPath: /home/leejaehong/log
            containerPath: /home/leejaehong/log
      kubeadmConfigPatches:
          - |
              kind: InitConfiguration
              nodeRegistration:
                kubeletExtraArgs:
                  anonymous-auth: "true"
                  authorization-mode: "AlwaysAllow"
    - role: worker
      extraMounts:
          - hostPath: /home/leejaehong/log
            containerPath: /home/leejaehong/log
      kubeadmConfigPatches:
          - |
              kind: InitConfiguration
              nodeRegistration:
                kubeletExtraArgs:
                  anonymous-auth: "true"
                  authorization-mode: "AlwaysAllow"
    - role: worker
      extraMounts:
          - hostPath: /home/leejaehong/log
            containerPath: /home/leejaehong/log
      kubeadmConfigPatches:
          - |
              kind: InitConfiguration
              nodeRegistration:
                kubeletExtraArgs:
                  anonymous-auth: "true"
                  authorization-mode: "AlwaysAllow"
    - role: worker
      extraMounts:
          - hostPath: /home/leejaehong/log
            containerPath: /home/leejaehong/log
      kubeadmConfigPatches:
          - |
              kind: InitConfiguration
              nodeRegistration:
                kubeletExtraArgs:
                  anonymous-auth: "true"
                  authorization-mode: "AlwaysAllow"
