apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-app2
  name: simple-app2
spec:
  replicas: 5
  selector:
    matchLabels:
      app: simple-app2
  template:
    metadata:
      labels:
        app: simple-app2
    spec:
      containers:
        - image: hong9lol/simple_app:latest
          imagePullPolicy: Always
          name: simple-app2-container1
          ports:
            - containerPort: 8081
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 5
          resources:
            limits:
              cpu: 400m
              memory: 128Mi
            requests:
              cpu: 200m
              memory: 64Mi
